server:
  port: 8080

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    hikari:
      connection-timeout: 30000 # default 30s
      maximum-pool-size: 10 # default 10
      max-lifetime: 1800000 # default 30 minutes

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
