server:
  port: 8080

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    hikari:
      connection-timeout: 30000 # default 30s
      maximum-pool-size: 10 # default 10
      max-lifetime: 1800000 # default 30 minutes

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  access-header: ACCESS_TOKEN
  refresh-header: REFRESH_TOKEN
  prefix: Bearer
  secret-key: Zi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXktZi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXkK
  access-token-validity-in-seconds: 60 # 1분
  refresh-token-validity-in-seconds: 259200 # 3일

springfox:
  documentation:
    swagger:
      use-model-v3: false
