server:
  port: 8080

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    hikari:
      connection-timeout: 30000 # default 30s
      maximum-pool-size: 10 # default 10
      max-lifetime: 1800000 # default 30 minutes

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  access-header: ACCESS_TOKEN
  prefix: Bearer
  secret-key: Zi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXktZi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400
