spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(LowN1n4w0Ep/DqLD8+q5Bq6AXM4b8e3V)
    password: ENC(OMvGcpZLpggFTiGNkqNe66Zq/SmJXF6o)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    import: "optional:configserver:"

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  access-header: Authorization
  refresh-header: REFRESH_TOKEN
  prefix: Bearer
  secret-key: Zi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXktZi1sYWItdGlja2V0aW5nLXByb2plY3Qtc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC1rZXkK
  access-token-validity-in-seconds: 60
  refresh-token-validity-in-seconds: 259200

tmdb:
  api-key: 0d1503b6dcbfe1c514299b5564c649b8
  read-access-token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZDE1MDNiNmRjYmZlMWM1MTQyOTliNTU2NGM2NDliOCIsInN1YiI6IjYyOWYwODRlNzI2ZmIxMTA2NDA4MjI2NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.rs8KZea8QLyashILiggWFx2s46lgUtzo-xSWoDgE58A
